// Code generated by MockGen. DO NOT EDIT.
// Source: usecase/subtask/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "reza/todolist-api/model"

	gomock "github.com/golang/mock/gomock"
)

// MockSubTaskUsecase is a mock of SubTaskUsecase interface.
type MockSubTaskUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockSubTaskUsecaseMockRecorder
}

// MockSubTaskUsecaseMockRecorder is the mock recorder for MockSubTaskUsecase.
type MockSubTaskUsecaseMockRecorder struct {
	mock *MockSubTaskUsecase
}

// NewMockSubTaskUsecase creates a new mock instance.
func NewMockSubTaskUsecase(ctrl *gomock.Controller) *MockSubTaskUsecase {
	mock := &MockSubTaskUsecase{ctrl: ctrl}
	mock.recorder = &MockSubTaskUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubTaskUsecase) EXPECT() *MockSubTaskUsecaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubTaskUsecase) Create(ctx context.Context, req model.CreateSubTaskRequest) (model.CreateResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(model.CreateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockSubTaskUsecaseMockRecorder) Create(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubTaskUsecase)(nil).Create), ctx, req)
}

// Detail mocks base method.
func (m *MockSubTaskUsecase) Detail(ctx context.Context, req model.DetailSubTaskRequest) (model.DetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, req)
	ret0, _ := ret[0].(model.DetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockSubTaskUsecaseMockRecorder) Detail(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockSubTaskUsecase)(nil).Detail), ctx, req)
}

// List mocks base method.
func (m *MockSubTaskUsecase) List(ctx context.Context, req model.ListSubTaskRequest) (*model.ListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, req)
	ret0, _ := ret[0].(*model.ListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockSubTaskUsecaseMockRecorder) List(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSubTaskUsecase)(nil).List), ctx, req)
}
