// Code generated by MockGen. DO NOT EDIT.
// Source: repository/gorm/interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	model "reza/todolist-api/model"

	gomock "github.com/golang/mock/gomock"
)

// MockTaskRepository is a mock of TaskRepository interface.
type MockTaskRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRepositoryMockRecorder
}

// MockTaskRepositoryMockRecorder is the mock recorder for MockTaskRepository.
type MockTaskRepositoryMockRecorder struct {
	mock *MockTaskRepository
}

// NewMockTaskRepository creates a new mock instance.
func NewMockTaskRepository(ctrl *gomock.Controller) *MockTaskRepository {
	mock := &MockTaskRepository{ctrl: ctrl}
	mock.recorder = &MockTaskRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRepository) EXPECT() *MockTaskRepositoryMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskRepository) CreateTask(ctx context.Context, req model.CreateTaskRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskRepositoryMockRecorder) CreateTask(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskRepository)(nil).CreateTask), ctx, req)
}

// DeleteSubTask mocks base method.
func (m *MockTaskRepository) DeleteSubTask(ctx context.Context, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSubTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSubTask indicates an expected call of DeleteSubTask.
func (mr *MockTaskRepositoryMockRecorder) DeleteSubTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSubTask", reflect.TypeOf((*MockTaskRepository)(nil).DeleteSubTask), ctx, taskID)
}

// DeleteTask mocks base method.
func (m *MockTaskRepository) DeleteTask(ctx context.Context, taskID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", ctx, taskID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskRepositoryMockRecorder) DeleteTask(ctx, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskRepository)(nil).DeleteTask), ctx, taskID)
}

// DetailTask mocks base method.
func (m *MockTaskRepository) DetailTask(ctx context.Context, req model.DetailTaskRequest) (*model.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetailTask", ctx, req)
	ret0, _ := ret[0].(*model.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetailTask indicates an expected call of DetailTask.
func (mr *MockTaskRepositoryMockRecorder) DetailTask(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetailTask", reflect.TypeOf((*MockTaskRepository)(nil).DetailTask), ctx, req)
}

// ListSubTask mocks base method.
func (m *MockTaskRepository) ListSubTask(pagination model.Pagination, search string, taskID int64) (*model.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSubTask", pagination, search, taskID)
	ret0, _ := ret[0].(*model.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSubTask indicates an expected call of ListSubTask.
func (mr *MockTaskRepositoryMockRecorder) ListSubTask(pagination, search, taskID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSubTask", reflect.TypeOf((*MockTaskRepository)(nil).ListSubTask), pagination, search, taskID)
}

// ListTask mocks base method.
func (m *MockTaskRepository) ListTask(pagination model.Pagination, search string) (*model.Pagination, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTask", pagination, search)
	ret0, _ := ret[0].(*model.Pagination)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTask indicates an expected call of ListTask.
func (mr *MockTaskRepositoryMockRecorder) ListTask(pagination, search interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTask", reflect.TypeOf((*MockTaskRepository)(nil).ListTask), pagination, search)
}

// UpdateTask mocks base method.
func (m *MockTaskRepository) UpdateTask(ctx context.Context, req model.Task) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTask", ctx, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTask indicates an expected call of UpdateTask.
func (mr *MockTaskRepositoryMockRecorder) UpdateTask(ctx, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTask", reflect.TypeOf((*MockTaskRepository)(nil).UpdateTask), ctx, req)
}
